spring.application.name=village

server.servlet.context-path=/api
# spring.datasource.url=jdbc:postgresql://ep-polished-lake-aob9utk3-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_Dmc1bTniO5PE

spring.datasource.url=jdbc:postgresql://localhost:5432/village_marketplace
spring.datasource.username=village_user
spring.datasource.password=postgres12345

spring.datasource.driver-class-name=org.postgresql.Driver

spring.graphql.path=/graphql

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key=${grop_api_key}
spring.ai.openai.base-url=https://api.groq.com/openai
# spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
# spring.ai.openai.chat.options.model=llama3-8b-8192
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

logging.level.org.springframework.ai=DEBUG


# for email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vikkityagi1998@gmail.com
spring.mail.password=zjohdigegxoyjiyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true