spring.application.name=village

server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://ep-floral-rain-ao6azn3k-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_F6Ld0yUiJjou

# spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
# spring.datasource.username=postgres
# spring.datasource.password=postgres

spring.graphql.path=/graphql

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key=${grop_api_key}
spring.ai.openai.base-url=https://api.groq.com/openai
# spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
# spring.ai.openai.chat.options.model=llama3-8b-8192
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

logging.level.org.springframework.ai=DEBUG


# for email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vikkityagi1998@gmail.com
spring.mail.password=zjohdigegxoyjiyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true